# Generated by Django 3.1.2 on 2020-10-25 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='eatual',
            new_name='atual',
        ),
    ]
