# Generated by Django 3.1.1 on 2020-10-05 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comunicante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.IntegerField()),
                ('descricao_situacao', models.CharField(max_length=300)),
                ('horario', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('forma', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.comunicante')),
            ],
        ),
        migrations.CreateModel(
            name='DireitoViolado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_direito', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.bairro')),
                ('cidade', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotacoes', models.ManyToManyField(to='app.Anotacao')),
                ('denuncia', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.denuncia')),
            ],
        ),
        migrations.CreateModel(
            name='Vitima',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('nome_responsavel', models.CharField(max_length=100)),
                ('estudante', models.BooleanField()),
                ('serie', models.CharField(max_length=100)),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.endereco')),
                ('escola', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.escola')),
                ('ocorrencias', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.ocorrencia')),
            ],
        ),
        migrations.AddField(
            model_name='denuncia',
            name='direito_violado',
            field=models.ManyToManyField(to='app.DireitoViolado'),
        ),
        migrations.AddField(
            model_name='comunicante',
            name='endereco',
            field=models.ManyToManyField(to='app.Endereco'),
        ),
        migrations.AddField(
            model_name='comunicante',
            name='meio_de_contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.contato'),
        ),
        migrations.AddField(
            model_name='anotacao',
            name='arquivos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.arquivo'),
        ),
    ]
