# Generated by Django 3.1.1 on 2020-10-10 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='escolha',
            field=models.CharField(choices=[(1, 'RG'), (2, 'CPF')], default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='comunicante',
            name='telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='documento',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
