# Generated by Django 3.1.2 on 2020-10-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201024_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='denuncia',
            old_name='endereco',
            new_name='endereco_denuncia',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='atual',
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
