# Generated by Django 3.1.2 on 2020-12-27 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201227_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao',
            name='arquivos',
            field=models.FileField(blank=True, null=True, upload_to='imagens_anotacao/'),
        ),
    ]
