# Generated by Django 3.1.1 on 2020-10-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201005_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicante',
            name='telefone',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.ManyToManyField(to='app.Bairro'),
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.ManyToManyField(to='app.Cidade'),
        ),
        migrations.RemoveField(
            model_name='escola',
            name='endereco',
        ),
        migrations.AddField(
            model_name='escola',
            name='endereco',
            field=models.ManyToManyField(to='app.Endereco'),
        ),
        migrations.RemoveField(
            model_name='vitima',
            name='endereco',
        ),
        migrations.AddField(
            model_name='vitima',
            name='endereco',
            field=models.ManyToManyField(to='app.Endereco'),
        ),
        migrations.RemoveField(
            model_name='vitima',
            name='ocorrencias',
        ),
        migrations.AddField(
            model_name='vitima',
            name='ocorrencias',
            field=models.ManyToManyField(to='app.Ocorrencia'),
        ),
    ]
