# Generated by Django 3.1.1 on 2020-10-05 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201005_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.bairro'),
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cidade',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='app.cidade'),
        ),
    ]
