# Generated by Django 3.1.2 on 2020-12-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201227_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacaoFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='imagens_anotacao/')),
            ],
        ),
        migrations.RemoveField(
            model_name='anotacao',
            name='arquivos',
        ),
        migrations.AddField(
            model_name='anotacao',
            name='arquivos',
            field=models.ManyToManyField(to='app.AnotacaoFile'),
        ),
    ]
