# Generated by Django 3.1.2 on 2021-01-18 04:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0007_auto_20210104_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('cpf', models.CharField(max_length=11)),
            ],
            bases=('auth.user', models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='conselheiro',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Secretaria',
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='conselheiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.servidor'),
        ),
        migrations.DeleteModel(
            name='Conselheiro',
        ),
    ]
