# Generated by Django 3.1.2 on 2021-01-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210118_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitima',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.escola'),
        ),
        migrations.AlterField(
            model_name='vitima',
            name='nome_responsavel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
