# Generated by Django 3.1.2 on 2021-01-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210121_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='vitimas',
            field=models.ManyToManyField(to='app.Vitima'),
        ),
    ]
