# Generated by Django 3.1.2 on 2021-01-22 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210121_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocorrencia',
            name='conselheiro',
        ),
        migrations.AddField(
            model_name='denuncia',
            name='conselheiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.servidor'),
        ),
    ]
