# Generated by Django 3.1.6 on 2021-03-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210320_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bairro',
            old_name='nome_bairro',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cidade',
            old_name='nome_cidade',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='direito',
            old_name='nome_direito',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='escola',
            old_name='nome_escola',
            new_name='nome',
        ),
    ]
