# Generated by Django 3.1.6 on 2021-05-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210505_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicante',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
