# Generated by Django 3.1.2 on 2020-12-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201227_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao',
            name='arquivos',
            field=models.ManyToManyField(blank=True, to='app.AnotacaoFile'),
        ),
    ]
