# Generated by Django 3.1.2 on 2021-01-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210118_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitima',
            name='enderecos',
            field=models.ManyToManyField(blank=True, to='app.Endereco'),
        ),
    ]
