# Generated by Django 3.1.2 on 2021-01-18 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_arquivo_ocorrencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='anotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.anotacao'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
