# Generated by Django 3.1.2 on 2021-01-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210118_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='vitimas',
            field=models.ManyToManyField(blank=True, null=True, to='app.Vitima'),
        ),
    ]
