# Generated by Django 3.1.6 on 2021-02-22 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210208_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='forma',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contato',
            name='tipo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo_de_logradouro',
            field=models.CharField(blank=True, choices=[('Rua', 'Rua'), ('Avenida', 'Avenida'), ('Praça', 'Praça'), ('Quadra', 'Quadra'), ('Alameda', 'Alameda'), ('Beco', 'Beco'), ('Vila', 'Vila'), ('Estrada', 'Estrada'), ('Passagem', 'Passagem'), ('Viela', 'Viela'), ('Servidão', 'Servidão')], max_length=20, null=True),
        ),
    ]
