# Generated by Django 3.1.6 on 2021-02-22 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210222_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='comunicante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.comunicante'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='escolha',
            field=models.CharField(blank=True, choices=[('rg', 'RG'), ('cpf', 'CPF')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='valor',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
