# Generated by Django 3.1.6 on 2021-03-21 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_log_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
