# Generated by Django 3.1.6 on 2021-03-21 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20210320_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
