# Generated by Django 3.1.6 on 2021-03-21 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210321_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direito',
            name='denuncia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.denuncia'),
        ),
    ]
